# API specification
api:
  # Replace with respective autodiscovery id
  autodiscoveryID: "00000000"
  
# Listener configuration
https:
  host: "0.0.0.0"
  port: "8082"
  
# API Configurations
slack-sys-api:
  http-listener:
    path: "/api/*"
  slack:
    host: "slack.com"
    port: "443"
    path: "/api"
    ping-url: "status.slack.com"
    response-timeout: "60000"
    connection-idle-timeout: "3000"
    http-frequency: "5000"
    http-reconnection-attempts: "2"
    access-token: "xoxb-3854933763063-4995077722481-a95bVTvjYb46Qf4N8OuwSrsk"
    
# Do not change the value of common.notifications.send=none, as it could cause a circular dependency
common:
  notifications:
    send: "none"
